import { AppItem, FolderItem } from '@/types/launcher';

export const INITIAL_APPS: AppItem[] = [
  // Dock Favorites (5 default)
  {
    id: 'phone',
    name: 'Phone',
    packageName: 'com.google.android.dialer',
    category: 'system',
    iconColor: '#1a73e8',
    iconBg: '#e8f0fe',
    iconType: 'svg',
    isFavorite: true,
    dockPosition: 0,
    notificationCount: 2,
    shortcuts: [
      { id: 'recent_mom', label: 'Call Mom', icon: 'phone-call' },
      { id: 'voicemail', label: 'Voicemail', icon: 'voicemail' },
      { id: 'keypad', label: 'Keypad', icon: 'grid' },
    ]
  },
  {
    id: 'messages',
    name: 'Messages',
    packageName: 'com.google.android.apps.messaging',
    category: 'google',
    iconColor: '#1a73e8',
    iconBg: '#ffffff',
    iconType: 'svg',
    isFavorite: true,
    dockPosition: 1,
    notificationCount: 5,
    shortcuts: [
      { id: 'new_chat', label: 'Start chat', icon: 'message-square-plus' },
      { id: 'contact_alex', label: 'Alex Rivers', icon: 'user' },
    ]
  },
  {
    id: 'lawnchair_settings',
    name: 'Lawnchair',
    packageName: 'app.lawnchair',
    category: 'system',
    iconColor: '#00897b',
    iconBg: '#e0f2f1',
    iconType: 'svg',
    isFavorite: true,
    dockPosition: 2,
    shortcuts: [
      { id: 'home_settings', label: 'Home settings', icon: 'settings' },
      { id: 'edit_icons', label: 'Edit icons', icon: 'palette' },
      { id: 'about', label: 'About Lawnchair', icon: 'info' },
    ]
  },
  {
    id: 'camera',
    name: 'Camera',
    packageName: 'com.google.android.GoogleCamera',
    category: 'system',
    iconColor: '#3c4043',
    iconBg: '#ffffff',
    iconType: 'svg',
    isFavorite: true,
    dockPosition: 3,
    shortcuts: [
      { id: 'take_selfie', label: 'Take a selfie', icon: 'camera' },
      { id: 'record_video', label: 'Record video', icon: 'video' },
      { id: 'portrait', label: 'Portrait mode', icon: 'user' },
    ]
  },
  {
    id: 'chrome',
    name: 'Chrome',
    packageName: 'com.android.chrome',
    category: 'google',
    iconColor: '#4285f4',
    iconBg: '#ffffff',
    iconType: 'svg',
    isFavorite: true,
    dockPosition: 4,
    shortcuts: [
      { id: 'new_tab', label: 'New tab', icon: 'plus' },
      { id: 'incognito', label: 'New incognito tab', icon: 'eye-off' },
    ]
  },

  // Home Screen Page 0 Apps
  {
    id: 'play_store',
    name: 'Play Store',
    packageName: 'com.android.vending',
    category: 'google',
    iconColor: '#0086f8',
    iconBg: '#ffffff',
    iconType: 'svg',
    homePosition: { page: 0, row: 2, col: 0 },
    shortcuts: [
      { id: 'my_apps', label: 'My apps & games', icon: 'layers' },
      { id: 'search_store', label: 'Search Play', icon: 'search' },
    ]
  },
  {
    id: 'photos',
    name: 'Photos',
    packageName: 'com.google.android.apps.photos',
    category: 'google',
    iconColor: '#ea4335',
    iconBg: '#ffffff',
    iconType: 'svg',
    homePosition: { page: 0, row: 2, col: 1 },
    shortcuts: [
      { id: 'search_photos', label: 'Search', icon: 'search' },
      { id: 'free_up_space', label: 'Free up space', icon: 'trash-2' },
    ]
  },
  {
    id: 'gmail',
    name: 'Gmail',
    packageName: 'com.google.android.gm',
    category: 'google',
    iconColor: '#ea4335',
    iconBg: '#ffffff',
    iconType: 'svg',
    homePosition: { page: 0, row: 2, col: 2 },
    notificationCount: 3,
    shortcuts: [
      { id: 'compose', label: 'Compose', icon: 'edit-3' },
      { id: 'work_mail', label: 'Work Inbox', icon: 'mail' },
    ]
  },
  {
    id: 'settings',
    name: 'Settings',
    packageName: 'com.android.settings',
    category: 'system',
    iconColor: '#5f6368',
    iconBg: '#e8eaed',
    iconType: 'svg',
    homePosition: { page: 0, row: 2, col: 3 },
    shortcuts: [
      { id: 'battery_settings', label: 'Battery', icon: 'battery-charging' },
      { id: 'network_settings', label: 'Network & internet', icon: 'wifi' },
      { id: 'display_settings', label: 'Wallpaper & style', icon: 'palette' },
    ]
  },

  // Home Screen Page 0 Row 3
  {
    id: 'maps',
    name: 'Maps',
    packageName: 'com.google.android.apps.maps',
    category: 'google',
    iconColor: '#34a853',
    iconBg: '#ffffff',
    iconType: 'svg',
    homePosition: { page: 0, row: 3, col: 0 },
    shortcuts: [
      { id: 'work', label: 'Work', icon: 'briefcase' },
      { id: 'home', label: 'Home', icon: 'home' },
    ]
  },
  {
    id: 'youtube',
    name: 'YouTube',
    packageName: 'com.google.android.youtube',
    category: 'media',
    iconColor: '#ff0000',
    iconBg: '#ffffff',
    iconType: 'svg',
    homePosition: { page: 0, row: 3, col: 1 },
    shortcuts: [
      { id: 'subscriptions', label: 'Subscriptions', icon: 'film' },
      { id: 'shorts', label: 'Shorts', icon: 'zap' },
      { id: 'search_yt', label: 'Search', icon: 'search' },
    ]
  },
  {
    id: 'spotify',
    name: 'Spotify',
    packageName: 'com.spotify.music',
    category: 'media',
    iconColor: '#1ed760',
    iconBg: '#121212',
    iconType: 'svg',
    homePosition: { page: 0, row: 3, col: 2 },
    shortcuts: [
      { id: 'liked_songs', label: 'Liked Songs', icon: 'heart' },
      { id: 'search_music', label: 'Search', icon: 'search' },
    ]
  },
  {
    id: 'clock',
    name: 'Clock',
    packageName: 'com.google.android.deskclock',
    category: 'tools',
    iconColor: '#1a73e8',
    iconBg: '#e8f0fe',
    iconType: 'svg',
    homePosition: { page: 0, row: 3, col: 3 },
    shortcuts: [
      { id: 'alarm', label: 'Set alarm', icon: 'alarm-clock' },
      { id: 'timer', label: 'New timer', icon: 'timer' },
      { id: 'stopwatch', label: 'Stopwatch', icon: 'clock' },
    ]
  },

  // Additional Installed Apps in App Drawer (All with 100% Lawnicons SVGs)
  {
    id: 'calculator',
    name: 'Calculator',
    packageName: 'com.google.android.calculator',
    category: 'tools',
    iconColor: '#1a73e8',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'calendar',
    name: 'Calendar',
    packageName: 'com.google.android.calendar',
    category: 'google',
    iconColor: '#1a73e8',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'drive',
    name: 'Drive',
    packageName: 'com.google.android.apps.docs',
    category: 'google',
    iconColor: '#0f9d58',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'files',
    name: 'Files',
    packageName: 'com.google.android.apps.nbu.files',
    category: 'system',
    iconColor: '#1a73e8',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'weather',
    name: 'Weather',
    packageName: 'com.google.android.apps.weather',
    category: 'tools',
    iconColor: '#4285f4',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'keep_notes',
    name: 'Keep Notes',
    packageName: 'com.google.android.keep',
    category: 'productivity',
    iconColor: '#fbbc04',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'discord',
    name: 'Discord',
    packageName: 'com.discord',
    category: 'social',
    iconColor: '#5865f2',
    iconBg: '#36393f',
    iconType: 'svg',
  },
  {
    id: 'facebook',
    name: 'Facebook',
    packageName: 'com.facebook.katana',
    category: 'social',
    iconColor: '#1877f2',
    iconBg: '#ffffff',
    iconType: 'svg',
    shortcuts: [
      { id: 'create_post', label: 'Create post', icon: 'edit-3' },
      { id: 'search_facebook', label: 'Search Facebook', icon: 'search' },
    ],
  },
  {
    id: 'github',
    name: 'GitHub',
    packageName: 'com.github.android',
    category: 'productivity',
    iconColor: '#24292e',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    packageName: 'com.whatsapp',
    category: 'social',
    iconColor: '#25d366',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'yt_music',
    name: 'YT Music',
    packageName: 'com.google.android.apps.youtube.music',
    category: 'media',
    iconColor: '#ff0000',
    iconBg: '#000000',
    iconType: 'svg',
  },
  {
    id: 'recorder',
    name: 'Recorder',
    packageName: 'com.google.android.apps.recorder',
    category: 'tools',
    iconColor: '#ea4335',
    iconBg: '#fce8e6',
    iconType: 'svg',
  },
  {
    id: 'contacts',
    name: 'Contacts',
    packageName: 'com.google.android.contacts',
    category: 'google',
    iconColor: '#1a73e8',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'pixel_tips',
    name: 'Pixel Tips',
    packageName: 'com.google.android.apps.tips',
    category: 'system',
    iconColor: '#ea4335',
    iconBg: '#fff',
    iconType: 'svg',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    packageName: 'org.telegram.messenger',
    category: 'social',
    iconColor: '#229ed9',
    iconBg: '#229ed9',
    iconType: 'svg',
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    packageName: 'com.twitter.android',
    category: 'social',
    iconColor: '#000000',
    iconBg: '#000000',
    iconType: 'svg',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    packageName: 'com.instagram.android',
    category: 'social',
    iconColor: '#e1306c',
    iconBg: '#e1306c',
    iconType: 'svg',
  },
  {
    id: 'reddit',
    name: 'Reddit',
    packageName: 'com.reddit.frontpage',
    category: 'social',
    iconColor: '#ff4500',
    iconBg: '#ff4500',
    iconType: 'svg',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    packageName: 'com.netflix.mediaclient',
    category: 'media',
    iconColor: '#e50914',
    iconBg: '#000000',
    iconType: 'svg',
  },
  {
    id: 'notion',
    name: 'Notion',
    packageName: 'notion.id',
    category: 'productivity',
    iconColor: '#000000',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'slack',
    name: 'Slack',
    packageName: 'com.Slack',
    category: 'productivity',
    iconColor: '#4a154b',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'twitch',
    name: 'Twitch',
    packageName: 'tv.twitch.android.app',
    category: 'media',
    iconColor: '#9146ff',
    iconBg: '#9146ff',
    iconType: 'svg',
  },
  {
    id: 'firefox',
    name: 'Firefox',
    packageName: 'org.mozilla.firefox',
    category: 'tools',
    iconColor: '#ff7139',
    iconBg: '#ffffff',
    iconType: 'svg',
  },
  {
    id: 'vlc',
    name: 'VLC',
    packageName: 'org.videolan.vlc',
    category: 'media',
    iconColor: '#ff8800',
    iconBg: '#ff8800',
    iconType: 'svg',
  }
];

export const INITIAL_FOLDERS: FolderItem[] = [
  {
    id: 'google_folder',
    name: 'Google',
    appIds: ['drive', 'calendar', 'files', 'keep_notes', 'contacts', 'pixel_tips'],
    homePosition: { page: 0, row: 1, col: 0 }
  },
  {
    id: 'media_folder',
    name: 'Social & Media',
    appIds: ['discord', 'whatsapp', 'github', 'yt_music', 'telegram', 'instagram'],
    homePosition: { page: 0, row: 1, col: 1 }
  }
];
