import { Wallpaper } from '@/types/launcher';

export const WALLPAPERS: Wallpaper[] = [
  {
    id: 'pixel9_obsidian',
    name: 'Pixel 9 Obsidian Glass',
    category: 'Pixel 9',
    url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=300&auto=format&fit=crop',
    palette: {
      id: 'obsidian_light',
      name: 'Obsidian Light',
      primary: '#4c626b',
      onPrimary: '#ffffff',
      primaryContainer: '#cfe6f1',
      onPrimaryContainer: '#061e27',
      secondary: '#4d616c',
      onSecondary: '#ffffff',
      secondaryContainer: '#cfe6f2',
      onSecondaryContainer: '#081e27',
      tertiary: '#5b5b7e',
      surface: '#f6fafd',
      onSurface: '#171c1f',
      surfaceVariant: '#dce4e9',
      onSurfaceVariant: '#40484c',
      outline: '#70787d',
      surfaceContainer: '#eaeef1',
      surfaceContainerHigh: '#e4e9ec',
      surfaceContainerHighest: '#dee3e6',
      surfaceContainerLow: '#f0f4f7',
      isDarkPalette: false,
    },
    darkPalette: {
      id: 'obsidian_dark',
      name: 'Obsidian Slate',
      primary: '#b3cad5',
      onPrimary: '#1e333c',
      primaryContainer: '#354a53',
      onPrimaryContainer: '#cfe6f1',
      secondary: '#b4cad5',
      onSecondary: '#1e333c',
      secondaryContainer: '#354a53',
      onSecondaryContainer: '#cfe6f2',
      tertiary: '#c4c3ea',
      surface: '#0f1417',
      onSurface: '#dee3e6',
      surfaceVariant: '#40484c',
      onSurfaceVariant: '#c0c8cd',
      outline: '#8a9297',
      surfaceContainer: '#1b2023',
      surfaceContainerHigh: '#252b2e',
      surfaceContainerHighest: '#303639',
      surfaceContainerLow: '#171c1f',
      isDarkPalette: true,
    }
  },
  {
    id: 'pixel9_hazel',
    name: 'Pixel 9 Hazel Sage',
    category: 'Pixel 9',
    url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=300&auto=format&fit=crop',
    palette: {
      id: 'sage_light',
      name: 'Sage Meadow',
      primary: '#3d6837',
      onPrimary: '#ffffff',
      primaryContainer: '#bef0b2',
      onPrimaryContainer: '#002203',
      secondary: '#53634f',
      onSecondary: '#ffffff',
      secondaryContainer: '#d6e8ce',
      onSecondaryContainer: '#111f0f',
      tertiary: '#386568',
      surface: '#f7fbf2',
      onSurface: '#181d17',
      surfaceVariant: '#dee5d8',
      onSurfaceVariant: '#424940',
      outline: '#72796f',
      surfaceContainer: '#ebf0e6',
      surfaceContainerHigh: '#e5eae0',
      surfaceContainerHighest: '#dfe5db',
      surfaceContainerLow: '#f1f6ec',
      isDarkPalette: false,
    },
    darkPalette: {
      id: 'sage_dark',
      name: 'Sage Forest Dark',
      primary: '#a3d397',
      onPrimary: '#0e380d',
      primaryContainer: '#264f21',
      onPrimaryContainer: '#bef0b2',
      secondary: '#baceb3',
      onSecondary: '#253423',
      secondaryContainer: '#3b4b38',
      onSecondaryContainer: '#d6e8ce',
      tertiary: '#a0cfd1',
      surface: '#10150f',
      onSurface: '#dfe5db',
      surfaceVariant: '#424940',
      onSurfaceVariant: '#c2c9bd',
      outline: '#8c9388',
      surfaceContainer: '#1c211b',
      surfaceContainerHigh: '#272c25',
      surfaceContainerHighest: '#323730',
      surfaceContainerLow: '#181d17',
      isDarkPalette: true,
    }
  },
  {
    id: 'pixel9_rose',
    name: 'Pixel 9 Rose Quartz',
    category: 'Material You',
    url: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=300&auto=format&fit=crop',
    palette: {
      id: 'rose_light',
      name: 'Rose Bloom',
      primary: '#8c4a60',
      onPrimary: '#ffffff',
      primaryContainer: '#ffd9e2',
      onPrimaryContainer: '#3a071d',
      secondary: '#74565f',
      onSecondary: '#ffffff',
      secondaryContainer: '#ffd9e2',
      onSecondaryContainer: '#2b151c',
      tertiary: '#7c5635',
      surface: '#fff8f8',
      onSurface: '#22191c',
      surfaceVariant: '#f2dde2',
      onSurfaceVariant: '#514347',
      outline: '#837377',
      surfaceContainer: '#f9eaee',
      surfaceContainerHigh: '#f3e4e9',
      surfaceContainerHighest: '#eddee3',
      surfaceContainerLow: '#fff0f4',
      isDarkPalette: false,
    },
    darkPalette: {
      id: 'rose_dark',
      name: 'Rose Twilight',
      primary: '#ffb0c8',
      onPrimary: '#541d32',
      primaryContainer: '#703348',
      onPrimaryContainer: '#ffd9e2',
      secondary: '#e3bdc6',
      onSecondary: '#422931',
      secondaryContainer: '#5a3f47',
      onSecondaryContainer: '#ffd9e2',
      tertiary: '#efbd94',
      surface: '#191114',
      onSurface: '#eddee3',
      surfaceVariant: '#514347',
      onSurfaceVariant: '#d5c2c6',
      outline: '#9e8c90',
      surfaceContainer: '#261d20',
      surfaceContainerHigh: '#31282a',
      surfaceContainerHighest: '#3d3235',
      surfaceContainerLow: '#22191c',
      isDarkPalette: true,
    }
  },
  {
    id: 'pixel9_amber',
    name: 'Pixel 9 Sunset Amber',
    category: 'Material You',
    url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=300&auto=format&fit=crop',
    palette: {
      id: 'amber_light',
      name: 'Sunset Amber',
      primary: '#855318',
      onPrimary: '#ffffff',
      primaryContainer: '#ffddb8',
      onPrimaryContainer: '#2b1700',
      secondary: '#715b41',
      onSecondary: '#ffffff',
      secondaryContainer: '#fdddbd',
      onSecondaryContainer: '#281805',
      tertiary: '#55643a',
      surface: '#fff8f4',
      onSurface: '#211a14',
      surfaceVariant: '#f0e0d0',
      onSurfaceVariant: '#4f4539',
      outline: '#817567',
      surfaceContainer: '#faece1',
      surfaceContainerHigh: '#f4e6db',
      surfaceContainerHighest: '#eee1d6',
      surfaceContainerLow: '#fff2ea',
      isDarkPalette: false,
    },
    darkPalette: {
      id: 'amber_dark',
      name: 'Amber Glow Dark',
      primary: '#fbba73',
      onPrimary: '#472a00',
      primaryContainer: '#663d00',
      onPrimaryContainer: '#ffddb8',
      secondary: '#dfc1a2',
      onSecondary: '#3f2d17',
      secondaryContainer: '#57432b',
      onSecondaryContainer: '#fdddbd',
      tertiary: '#bdcc9c',
      surface: '#19120c',
      onSurface: '#eee1d6',
      surfaceVariant: '#4f4539',
      onSurfaceVariant: '#d3c4b5',
      outline: '#9c8e80',
      surfaceContainer: '#261e18',
      surfaceContainerHigh: '#312922',
      surfaceContainerHighest: '#3d342c',
      surfaceContainerLow: '#211a14',
      isDarkPalette: true,
    }
  },
  {
    id: 'lawnchair_sky',
    name: 'Lawnchair Classic Sky',
    category: 'Lawnchair',
    url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=300&auto=format&fit=crop',
    palette: {
      id: 'sky_light',
      name: 'Lawnchair Cyan',
      primary: '#00677d',
      onPrimary: '#ffffff',
      primaryContainer: '#b5ebff',
      onPrimaryContainer: '#001f28',
      secondary: '#4b626a',
      onSecondary: '#ffffff',
      secondaryContainer: '#cee7f0',
      onSecondaryContainer: '#061e25',
      tertiary: '#595c7e',
      surface: '#f5fbfe',
      onSurface: '#171d1e',
      surfaceVariant: '#dbe4e8',
      onSurfaceVariant: '#3f484b',
      outline: '#70797c',
      surfaceContainer: '#e9eff2',
      surfaceContainerHigh: '#e3e9ec',
      surfaceContainerHighest: '#dde4e7',
      surfaceContainerLow: '#eff5f8',
      isDarkPalette: false,
    },
    darkPalette: {
      id: 'sky_dark',
      name: 'Lawnchair Deep Ocean',
      primary: '#86d1ec',
      onPrimary: '#003542',
      primaryContainer: '#004d5f',
      onPrimaryContainer: '#b5ebff',
      secondary: '#b2cbd4',
      onSecondary: '#1d343b',
      secondaryContainer: '#344a52',
      onSecondaryContainer: '#cee7f0',
      tertiary: '#c2c4eb',
      surface: '#0f1416',
      onSurface: '#dde4e7',
      surfaceVariant: '#3f484b',
      onSurfaceVariant: '#bfc8cc',
      outline: '#899296',
      surfaceContainer: '#1b2123',
      surfaceContainerHigh: '#262b2d',
      surfaceContainerHighest: '#303638',
      surfaceContainerLow: '#171d1e',
      isDarkPalette: true,
    }
  },
  {
    id: 'amoled_minimal',
    name: 'Pitch Dark Minimal',
    category: 'Minimal',
    url: 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031?q=80&w=300&auto=format&fit=crop',
    palette: {
      id: 'mono_light',
      name: 'Monochrome Minimal Light',
      primary: '#5f6368',
      onPrimary: '#ffffff',
      primaryContainer: '#e8eaed',
      onPrimaryContainer: '#1f1f1f',
      secondary: '#5f6368',
      onSecondary: '#ffffff',
      secondaryContainer: '#e8eaed',
      onSecondaryContainer: '#1f1f1f',
      tertiary: '#5f6368',
      surface: '#ffffff',
      onSurface: '#1f1f1f',
      surfaceVariant: '#e1e3e1',
      onSurfaceVariant: '#444746',
      outline: '#747775',
      surfaceContainer: '#f0f4f9',
      surfaceContainerHigh: '#e9eef6',
      surfaceContainerHighest: '#e3e8ef',
      surfaceContainerLow: '#f7f9fc',
      isDarkPalette: false,
    },
    darkPalette: {
      id: 'mono_dark',
      name: 'Pitch Black AMOLED',
      primary: '#e3e3e3',
      onPrimary: '#000000',
      primaryContainer: '#282a2c',
      onPrimaryContainer: '#ffffff',
      secondary: '#c4c7c5',
      onSecondary: '#1e1f20',
      secondaryContainer: '#333537',
      onSecondaryContainer: '#e3e3e3',
      tertiary: '#e3e3e3',
      surface: '#000000',
      onSurface: '#ffffff',
      surfaceVariant: '#282a2c',
      onSurfaceVariant: '#c4c7c5',
      outline: '#8e918f',
      surfaceContainer: '#0a0a0a',
      surfaceContainerHigh: '#141414',
      surfaceContainerHighest: '#1f1f1f',
      surfaceContainerLow: '#050505',
      isDarkPalette: true,
    }
  }
];
